// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuikFormatDesktop.Database;

#nullable disable

namespace QuikFormatDesktop.Migrations
{
    [DbContext(typeof(QfDbContext))]
    partial class QfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("QuikFormatDesktop.Models.Alignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Alignment1")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("alignment");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Alignment1" }, "IX_alignment_alignment")
                        .IsUnique();

                    b.ToTable("alignment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alignment1 = "left"
                        },
                        new
                        {
                            Id = 2,
                            Alignment1 = "right"
                        },
                        new
                        {
                            Id = 3,
                            Alignment1 = "center"
                        },
                        new
                        {
                            Id = 4,
                            Alignment1 = "both"
                        },
                        new
                        {
                            Id = 5,
                            Alignment1 = "top"
                        },
                        new
                        {
                            Id = 6,
                            Alignment1 = "bottom"
                        });
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.Font", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FontName")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("font_name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FontName" }, "IX_font_font_name")
                        .IsUnique();

                    b.ToTable("font", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FontName = "Times New Roman"
                        },
                        new
                        {
                            Id = 2,
                            FontName = "Arial"
                        },
                        new
                        {
                            Id = 3,
                            FontName = "Calibri"
                        });
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.FormulaStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("EmptyLineAround")
                        .HasColumnType("bool")
                        .HasColumnName("empty_line_around");

                    b.Property<int?>("Marker")
                        .HasColumnType("INTEGER")
                        .HasColumnName("marker");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.Property<bool>("Numeration")
                        .HasColumnType("bool")
                        .HasColumnName("numeration");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("Marker");

                    b.HasIndex("Position");

                    b.HasIndex(new[] { "Name" }, "IX_formula_style_name")
                        .IsUnique();

                    b.ToTable("formula_style", (string)null);
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.GlobalStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AlignmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alignment");

                    b.Property<double>("BottomMargin")
                        .HasColumnType("REAL")
                        .HasColumnName("bottom_margin");

                    b.Property<int?>("LastNoNumberingPage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_no_numbering_page");

                    b.Property<double>("LeftMargin")
                        .HasColumnType("REAL")
                        .HasColumnName("left_margin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.Property<double>("RightMargin")
                        .HasColumnType("REAL")
                        .HasColumnName("right_margin");

                    b.Property<string>("SpecialColontitul")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("special_colontitul");

                    b.Property<double>("TopMargin")
                        .HasColumnType("REAL")
                        .HasColumnName("top_margin");

                    b.HasKey("Id");

                    b.HasIndex("AlignmentId");

                    b.HasIndex(new[] { "Name" }, "IX_global_style_name")
                        .IsUnique();

                    b.ToTable("global_style", (string)null);
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.Marker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Marker1")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("marker");

                    b.Property<int>("MarkerType")
                        .HasColumnType("INT")
                        .HasColumnName("marker_type");

                    b.HasKey("Id");

                    b.HasIndex("MarkerType");

                    b.HasIndex(new[] { "Marker1" }, "IX_marker_marker")
                        .IsUnique();

                    b.ToTable("marker", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Marker1 = "&#8211;",
                            MarkerType = 1
                        },
                        new
                        {
                            Id = 2,
                            Marker1 = "&#8226;",
                            MarkerType = 1
                        },
                        new
                        {
                            Id = 3,
                            Marker1 = "&#8227;",
                            MarkerType = 1
                        },
                        new
                        {
                            Id = 4,
                            Marker1 = "–",
                            MarkerType = 1
                        },
                        new
                        {
                            Id = 5,
                            Marker1 = "$.",
                            MarkerType = 2
                        },
                        new
                        {
                            Id = 6,
                            Marker1 = "$)",
                            MarkerType = 2
                        },
                        new
                        {
                            Id = 7,
                            Marker1 = "($)",
                            MarkerType = 2
                        });
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.MarkerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(13)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Type" }, "IX_marker_type_type")
                        .IsUnique();

                    b.ToTable("marker_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "marked"
                        },
                        new
                        {
                            Id = 2,
                            Type = "numbered"
                        });
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.NumberingStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Marker")
                        .HasColumnType("INTEGER")
                        .HasColumnName("marker");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Marker");

                    b.HasIndex(new[] { "Name" }, "IX_numbering_style_name")
                        .IsUnique();

                    b.ToTable("numbering_style", (string)null);
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.ParagraphStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double?>("AfterInterval")
                        .HasColumnType("REAL")
                        .HasColumnName("after_interval");

                    b.Property<int>("Alignment")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alignment");

                    b.Property<double?>("BeforeInterval")
                        .HasColumnType("REAL")
                        .HasColumnName("before_interval");

                    b.Property<bool>("ContextualSpacing")
                        .HasColumnType("boolean")
                        .HasColumnName("contextual_spacing");

                    b.Property<double?>("FirstLineIndent")
                        .HasColumnType("REAL")
                        .HasColumnName("first_line_indent");

                    b.Property<double>("IntervalInText")
                        .HasColumnType("REAL")
                        .HasColumnName("interval_in_text");

                    b.Property<double?>("LeftIndent")
                        .HasColumnType("REAL")
                        .HasColumnName("left_indent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.Property<double?>("RightIndent")
                        .HasColumnType("REAL")
                        .HasColumnName("right_indent");

                    b.HasKey("Id");

                    b.HasIndex("Alignment");

                    b.HasIndex(new[] { "Name" }, "IX_paragraph_style_name")
                        .IsUnique();

                    b.ToTable("paragraph_style", (string)null);
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.PictureStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("EmptyLineAround")
                        .HasColumnType("bool")
                        .HasColumnName("empty_line_around");

                    b.Property<bool>("GenerateLabel")
                        .HasColumnType("boolean")
                        .HasColumnName("generate_label");

                    b.Property<string>("LabelValue")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("label_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.Property<int>("ParagraphStyle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paragraph_style");

                    b.HasKey("Id");

                    b.HasIndex("ParagraphStyle");

                    b.HasIndex(new[] { "Name" }, "IX_picture_style_name")
                        .IsUnique();

                    b.ToTable("picture_style", (string)null);
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Position1")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Position1" }, "IX_position_position")
                        .IsUnique();

                    b.ToTable("position", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Position1 = "centerleft"
                        },
                        new
                        {
                            Id = 2,
                            Position1 = "centerright"
                        },
                        new
                        {
                            Id = 3,
                            Position1 = "rightleft"
                        },
                        new
                        {
                            Id = 4,
                            Position1 = "leftright"
                        });
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.TableStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Alignment")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alignment");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("char(7)")
                        .HasColumnName("border_color");

                    b.Property<int>("BorderThikness")
                        .HasColumnType("INTEGER")
                        .HasColumnName("border_thikness");

                    b.Property<double>("CellPadding")
                        .HasColumnType("REAL")
                        .HasColumnName("cell_padding");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.Property<int>("ParagraphStyle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paragraph_style");

                    b.Property<int>("TextStyle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("text_style");

                    b.HasKey("Id");

                    b.HasIndex("Alignment");

                    b.HasIndex("ParagraphStyle");

                    b.HasIndex("TextStyle");

                    b.HasIndex(new[] { "Name" }, "IX_table_style_name")
                        .IsUnique();

                    b.ToTable("table_style", (string)null);
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("FormulaStyle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("formula_style");

                    b.Property<int?>("GlobalStyle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("global_style");

                    b.Property<int?>("MarkedNumberingStyle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("marked_numbering_style");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.Property<int?>("NumberedNumberingStyle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numbered_numbering_style");

                    b.Property<int?>("ParagraphStyle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paragraph_style");

                    b.Property<int?>("PictureStyle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("picture_style");

                    b.Property<int?>("TableStyle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("table_style");

                    b.Property<int?>("TextStyle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("text_style");

                    b.HasKey("Id");

                    b.HasIndex("FormulaStyle");

                    b.HasIndex("GlobalStyle");

                    b.HasIndex("MarkedNumberingStyle");

                    b.HasIndex("NumberedNumberingStyle");

                    b.HasIndex("ParagraphStyle");

                    b.HasIndex("PictureStyle");

                    b.HasIndex("TableStyle");

                    b.HasIndex("TextStyle");

                    b.HasIndex(new[] { "Name" }, "IX_template_name")
                        .IsUnique();

                    b.ToTable("template", (string)null);
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.TextStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Font")
                        .HasColumnType("INTEGER")
                        .HasColumnName("font");

                    b.Property<int>("FontSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("font_size");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Font");

                    b.HasIndex(new[] { "Name" }, "IX_text_style_name")
                        .IsUnique();

                    b.ToTable("text_style", (string)null);
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.FormulaStyle", b =>
                {
                    b.HasOne("QuikFormatDesktop.Models.Marker", "MarkerNavigation")
                        .WithMany("FormulaStyles")
                        .HasForeignKey("Marker")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuikFormatDesktop.Models.Position", "PositionNavigation")
                        .WithMany("FormulaStyles")
                        .HasForeignKey("Position")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkerNavigation");

                    b.Navigation("PositionNavigation");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.GlobalStyle", b =>
                {
                    b.HasOne("QuikFormatDesktop.Models.Alignment", "AlignmentNavigation")
                        .WithMany("GlobalStyles")
                        .HasForeignKey("AlignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlignmentNavigation");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.Marker", b =>
                {
                    b.HasOne("QuikFormatDesktop.Models.MarkerType", "MarkerTypeNavigation")
                        .WithMany("Markers")
                        .HasForeignKey("MarkerType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkerTypeNavigation");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.NumberingStyle", b =>
                {
                    b.HasOne("QuikFormatDesktop.Models.Marker", "MarkerNavigation")
                        .WithMany("NumberingStyles")
                        .HasForeignKey("Marker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkerNavigation");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.ParagraphStyle", b =>
                {
                    b.HasOne("QuikFormatDesktop.Models.Alignment", "AlignmentNavigation")
                        .WithMany("ParagraphStyles")
                        .HasForeignKey("Alignment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlignmentNavigation");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.PictureStyle", b =>
                {
                    b.HasOne("QuikFormatDesktop.Models.ParagraphStyle", "ParagraphStyleNavigation")
                        .WithMany("PictureStyles")
                        .HasForeignKey("ParagraphStyle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParagraphStyleNavigation");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.TableStyle", b =>
                {
                    b.HasOne("QuikFormatDesktop.Models.Alignment", "AlignmentNavigation")
                        .WithMany("TableStyles")
                        .HasForeignKey("Alignment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuikFormatDesktop.Models.ParagraphStyle", "ParagraphStyleNavigation")
                        .WithMany("TableStyles")
                        .HasForeignKey("ParagraphStyle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuikFormatDesktop.Models.TextStyle", "TextStyleNavigation")
                        .WithMany("TableStyles")
                        .HasForeignKey("TextStyle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlignmentNavigation");

                    b.Navigation("ParagraphStyleNavigation");

                    b.Navigation("TextStyleNavigation");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.Template", b =>
                {
                    b.HasOne("QuikFormatDesktop.Models.FormulaStyle", "FormulaStyleNavigation")
                        .WithMany("Templates")
                        .HasForeignKey("FormulaStyle");

                    b.HasOne("QuikFormatDesktop.Models.GlobalStyle", "GlobalStyleNavigation")
                        .WithMany("TemplateGlobalStyleNavigations")
                        .HasForeignKey("GlobalStyle");

                    b.HasOne("QuikFormatDesktop.Models.NumberingStyle", "MarkedNumberingStyleNavigation")
                        .WithMany("TemplateMarkedNumberingStyleNavigations")
                        .HasForeignKey("MarkedNumberingStyle");

                    b.HasOne("QuikFormatDesktop.Models.NumberingStyle", "NumberedNumberingStyleNavigation")
                        .WithMany("TemplateNumberedNumberingStyleNavigations")
                        .HasForeignKey("NumberedNumberingStyle");

                    b.HasOne("QuikFormatDesktop.Models.ParagraphStyle", "ParagraphStyleNavigation")
                        .WithMany("Templates")
                        .HasForeignKey("ParagraphStyle");

                    b.HasOne("QuikFormatDesktop.Models.PictureStyle", "PictureStyleNavigation")
                        .WithMany("Templates")
                        .HasForeignKey("PictureStyle");

                    b.HasOne("QuikFormatDesktop.Models.TableStyle", "TableStyleNavigation")
                        .WithMany("Templates")
                        .HasForeignKey("TableStyle");

                    b.HasOne("QuikFormatDesktop.Models.TextStyle", "TextStyleNavigation")
                        .WithMany("TemplateTextStyleNavigations")
                        .HasForeignKey("TextStyle");

                    b.Navigation("FormulaStyleNavigation");

                    b.Navigation("GlobalStyleNavigation");

                    b.Navigation("MarkedNumberingStyleNavigation");

                    b.Navigation("NumberedNumberingStyleNavigation");

                    b.Navigation("ParagraphStyleNavigation");

                    b.Navigation("PictureStyleNavigation");

                    b.Navigation("TableStyleNavigation");

                    b.Navigation("TextStyleNavigation");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.TextStyle", b =>
                {
                    b.HasOne("QuikFormatDesktop.Models.Font", "FontNavigation")
                        .WithMany("TextStyles")
                        .HasForeignKey("Font")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FontNavigation");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.Alignment", b =>
                {
                    b.Navigation("GlobalStyles");

                    b.Navigation("ParagraphStyles");

                    b.Navigation("TableStyles");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.Font", b =>
                {
                    b.Navigation("TextStyles");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.FormulaStyle", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.GlobalStyle", b =>
                {
                    b.Navigation("TemplateGlobalStyleNavigations");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.Marker", b =>
                {
                    b.Navigation("FormulaStyles");

                    b.Navigation("NumberingStyles");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.MarkerType", b =>
                {
                    b.Navigation("Markers");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.NumberingStyle", b =>
                {
                    b.Navigation("TemplateMarkedNumberingStyleNavigations");

                    b.Navigation("TemplateNumberedNumberingStyleNavigations");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.ParagraphStyle", b =>
                {
                    b.Navigation("PictureStyles");

                    b.Navigation("TableStyles");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.PictureStyle", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.Position", b =>
                {
                    b.Navigation("FormulaStyles");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.TableStyle", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("QuikFormatDesktop.Models.TextStyle", b =>
                {
                    b.Navigation("TableStyles");

                    b.Navigation("TemplateTextStyleNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
